import Fastify from 'fastify';
import fastifyJwt from '@fastify/jwt';
import fastifyCors from '@fastify/cors';
import fastifyHelmet from '@fastify/helmet';
import fastifySwagger from '@fastify/swagger';
import fastifySwaggerUi from '@fastify/swagger-ui';
import { Pool } from 'pg';
import { drizzle } from 'drizzle-orm/node-postgres';
import { z } from 'zod';
import { parseEnv, baseEnvSchema } from '@tik-live-pro/config';
import { createLogger } from '@tik-live-pro/logger';
import { NatsJetStreamClient, ensureStreams, Subjects } from '@tik-live-pro/events';
import { StringCodec, consumerOpts, createInbox } from 'nats';
import { randomUUID } from 'node:crypto';
import { registerNotificationsRoutes } from './interfaces/http/notifications.routes.js';
import { notifications } from './infrastructure/db/schema.js';
import type {
  SessionStatusChangedPayload,
  PaymentFailedPayload,
} from '@tik-live-pro/events';
import type { BaseEvent } from '@tik-live-pro/shared-types';

const envSchema = baseEnvSchema.extend({
  DATABASE_URL: z.string().url(),
  JWT_SECRET: z.string().min(64),
});

const env = parseEnv(envSchema);
const logger = createLogger('notifications-service', { level: env.LOG_LEVEL });

async function bootstrap(): Promise<void> {
  const pool = new Pool({ connectionString: env.DATABASE_URL });
  const db = drizzle(pool);

  const nats = new NatsJetStreamClient();
  await nats.connect({ servers: [env.NATS_URL], name: 'notifications-service' });
  logger.info({ natsUrl: env.NATS_URL }, 'Connected to NATS');
  await ensureStreams(nats.getJetStreamManager());

  const fastify = Fastify({
    logger: false,
    trustProxy: true,
    ajv: { customOptions: { keywords: ['example'] } },
  });

  await fastify.register(fastifyHelmet);
  await fastify.register(fastifyCors, {
    origin: env.NODE_ENV === 'production'
      ? ['https://tiklivepro.me', 'https://app.tiklivepro.me']
      : true,
    credentials: true,
  });
  await fastify.register(fastifyJwt, { secret: env.JWT_SECRET });

  // ---------------------------------------------------------------------------
  // OpenAPI / Swagger
  // ---------------------------------------------------------------------------
  await fastify.register(fastifySwagger, {
    openapi: {
      openapi: '3.1.0',
      info: {
        title: 'TikLivePro — Notifications Service',
        description: `
Creates and delivers in-app notifications triggered by platform events.

## Notification Sources
Notifications are generated by consuming NATS JetStream events:
| Subject | Notification Type | Description |
|---|---|---|
| \`session.started\` | \`session_started\` | Your live stream is now live |
| \`session.ended\` | \`session_ended\` | Your live stream has ended |
| \`stream.error\` | \`stream_error\` | A streaming error occurred |
| \`billing.subscription.updated\` | \`billing_event\` | Subscription status changed |
| \`integration.account.connected\` | \`account_connected\` | New social account connected |

## Authorization
All endpoints require a JWT Bearer token.
      `.trim(),
        version: '1.0.0',
        contact: { name: 'TikLivePro Engineering', email: 'engineering@tiklivepro.pro' },
        license: { name: 'Proprietary' },
      },
      servers: [
        {
          url: 'http://localhost:{port}',
          description: 'Local development',
          variables: { port: { default: String(env.PORT), description: 'Service HTTP port' } },
        },
      ],
      components: {
        securitySchemes: {
          BearerAuth: {
            type: 'http',
            scheme: 'bearer',
            bearerFormat: 'JWT',
            description: 'JWT access token from POST /auth/login.',
          },
        },
      },
      tags: [
        { name: 'Notifications', description: 'In-app notification management.' },
        { name: 'Health', description: 'Kubernetes liveness / readiness probes.' },
      ],
    },
  });

  await fastify.register(fastifySwaggerUi, {
    routePrefix: '/docs',
    uiConfig: {
      docExpansion: 'full',
      deepLinking: true,
      persistAuthorization: true,
      displayRequestDuration: true,
      filter: true,
    },
    staticCSP: true,
  });

  registerNotificationsRoutes(fastify, { db });

  fastify.get(
    '/health',
    {
      schema: {
        tags: ['Health'],
        summary: 'Liveness probe',
        response: {
          200: { description: 'Service is alive.', type: 'object', properties: { status: { type: 'string', enum: ['ok'] }, service: { type: 'string' } } },
        },
      },
    },
    async () => ({ status: 'ok', service: 'notifications' }),
  );

  fastify.get(
    '/ready',
    {
      schema: {
        tags: ['Health'],
        summary: 'Readiness probe',
        response: {
          200: { description: 'Service is ready.', type: 'object', properties: { status: { type: 'string', enum: ['ready'] } } },
          503: { description: 'Service is not ready.', type: 'object', properties: { status: { type: 'string' }, message: { type: 'string' } } },
        },
      },
    },
    async (_req, reply) => {
      try {
        await pool.query('SELECT 1');
        return { status: 'ready' };
      } catch {
        return reply.status(503).send({ status: 'error', message: 'Database connection failed' });
      }
    },
  );

  await fastify.listen({ port: env.PORT, host: '0.0.0.0' });
  logger.info({ port: env.PORT }, 'Notifications service listening — docs at /docs');

  // ---------------------------------------------------------------------------
  // NATS event consumers — create in-app notifications from platform events
  // ---------------------------------------------------------------------------
  const sc = StringCodec();

  async function insertNotification(userId: string, type: string, title: string, body: string, metadata?: Record<string, unknown>): Promise<void> {
    await db.insert(notifications).values({ id: randomUUID(), userId, type, title, body, metadata, isRead: false, createdAt: new Date() })
      .onConflictDoNothing();
  }

  async function consumeSessionLive(): Promise<void> {
    const js = nats.getJetStream();
    const opts = consumerOpts();
    opts.durable('notifications-session-live');
    opts.ackExplicit();
    opts.deliverNew();
    opts.deliverTo(createInbox());
    try {
      const sub = await js.subscribe(Subjects.SESSION_LIVE, opts);
      for await (const msg of sub) {
        try {
          const event = JSON.parse(sc.decode(msg.data)) as BaseEvent<SessionStatusChangedPayload>;
          await insertNotification(
            event.payload.userId,
            'session_started',
            'Your stream is live!',
            'Your live session has started successfully.',
            { sessionId: event.payload.sessionId },
          );
          msg.ack();
        } catch (err) {
          logger.error({ err }, 'Failed to handle SESSION_LIVE for notification');
          msg.nak();
        }
      }
    } catch (err) {
      logger.error({ err }, 'Failed to subscribe to SESSION_LIVE');
    }
  }

  async function consumeSessionEnded(): Promise<void> {
    const js = nats.getJetStream();
    const opts = consumerOpts();
    opts.durable('notifications-session-ended');
    opts.ackExplicit();
    opts.deliverNew();
    opts.deliverTo(createInbox());
    try {
      const sub = await js.subscribe(Subjects.SESSION_ENDED, opts);
      for await (const msg of sub) {
        try {
          const event = JSON.parse(sc.decode(msg.data)) as BaseEvent<SessionStatusChangedPayload>;
          await insertNotification(
            event.payload.userId,
            'session_ended',
            'Stream ended',
            'Your live session has ended.',
            { sessionId: event.payload.sessionId },
          );
          msg.ack();
        } catch (err) {
          logger.error({ err }, 'Failed to handle SESSION_ENDED for notification');
          msg.nak();
        }
      }
    } catch (err) {
      logger.error({ err }, 'Failed to subscribe to SESSION_ENDED');
    }
  }

  async function consumePaymentFailed(): Promise<void> {
    const js = nats.getJetStream();
    const opts = consumerOpts();
    opts.durable('notifications-payment-failed');
    opts.ackExplicit();
    opts.deliverNew();
    opts.deliverTo(createInbox());
    try {
      const sub = await js.subscribe(Subjects.BILLING_PAYMENT_FAILED, opts);
      for await (const msg of sub) {
        try {
          const event = JSON.parse(sc.decode(msg.data)) as BaseEvent<PaymentFailedPayload>;
          await insertNotification(
            event.payload.userId,
            'billing_event',
            'Payment failed',
            'Your payment could not be processed. Please update your payment method.',
          );
          msg.ack();
        } catch (err) {
          logger.error({ err }, 'Failed to handle BILLING_PAYMENT_FAILED for notification');
          msg.nak();
        }
      }
    } catch (err) {
      logger.error({ err }, 'Failed to subscribe to BILLING_PAYMENT_FAILED');
    }
  }

  void consumeSessionLive();
  void consumeSessionEnded();
  void consumePaymentFailed();

  const shutdown = async (): Promise<void> => {
    await fastify.close();
    await nats.drain();
    await pool.end();
    process.exit(0);
  };
  process.on('SIGTERM', () => { void shutdown(); });
  process.on('SIGINT', () => { void shutdown(); });
}

bootstrap().catch((err: unknown) => {
  logger.error(err, 'Failed to start Notifications service');
  process.exit(1);
});
