import type { FastifyInstance } from 'fastify';

// ---------------------------------------------------------------------------
// Reusable schema fragments
// ---------------------------------------------------------------------------

const bearerAuth = [{ BearerAuth: [] }];

const errorSchema = (description: string) => ({
  description,
  type: 'object',
  required: ['error'],
  properties: {
    error: {
      type: 'object',
      required: ['code', 'message'],
      properties: {
        code: { type: 'string', description: 'Machine-readable error code.', example: 'NOT_FOUND' },
        message: { type: 'string', description: 'Human-readable error message.', example: 'Notification not found' },
      },
    },
  },
});

const notificationSchema = {
  type: 'object',
  description: 'An in-app notification for a user.',
  properties: {
    id: { type: 'string', format: 'uuid', description: 'Unique notification ID.' },
    type: {
      type: 'string',
      enum: ['session_started', 'session_ended', 'stream_error', 'billing_event', 'account_connected'],
      description: 'Notification type — determines the icon and routing in the client.',
      example: 'session_started',
    },
    title: {
      type: 'string',
      description: 'Short notification title (localized on the client using the i18n key).',
      example: 'Stream started',
    },
    body: {
      type: 'string',
      description: 'Full notification body text.',
      example: 'Your live session is now live on TikTok and Facebook.',
    },
    metadata: {
      type: 'object',
      description: 'Optional structured data related to the notification (e.g., sessionId for navigation).',
      additionalProperties: true,
      example: { sessionId: 'b2c3d4e5-f6a7-8901-bcde-f12345678901' },
    },
    isRead: {
      type: 'boolean',
      description: 'Whether the user has read this notification.',
      example: false,
    },
    createdAt: {
      type: 'string',
      format: 'date-time',
      description: 'ISO 8601 timestamp of when the notification was created.',
    },
  },
};

// ---------------------------------------------------------------------------

export function registerNotificationsRoutes(fastify: FastifyInstance): void {
  // GET /notifications -------------------------------------------------------
  fastify.get(
    '/notifications',
    {
      schema: {
        tags: ['Notifications'],
        summary: 'List notifications',
        description: `
Returns a paginated list of in-app notifications for the authenticated user, sorted by creation time (newest first).

Notifications are generated by the \`notifications\` service in response to NATS events:
| NATS Subject | Notification Type |
|---|---|
| \`session.started\` | \`session_started\` |
| \`session.ended\` | \`session_ended\` |
| \`stream.error\` | \`stream_error\` |
| \`billing.subscription.updated\` | \`billing_event\` |
| \`integration.account.connected\` | \`account_connected\` |
        `.trim(),
        security: bearerAuth,
        querystring: {
          type: 'object',
          properties: {
            unreadOnly: {
              type: 'boolean',
              default: false,
              description: 'When `true`, returns only unread notifications.',
            },
            page: {
              type: 'integer',
              minimum: 1,
              default: 1,
              description: 'Page number (1-based).',
            },
            pageSize: {
              type: 'integer',
              minimum: 1,
              maximum: 50,
              default: 20,
              description: 'Number of notifications per page. Maximum 50.',
            },
          },
        },
        response: {
          200: {
            description: 'Paginated notification list.',
            type: 'object',
            required: ['data'],
            properties: {
              data: {
                type: 'object',
                required: ['items', 'total', 'unreadCount', 'page', 'pageSize', 'hasNextPage'],
                properties: {
                  items: {
                    type: 'array',
                    items: notificationSchema,
                  },
                  total: {
                    type: 'integer',
                    description: 'Total number of notifications (applying the unreadOnly filter if set).',
                    example: 5,
                  },
                  unreadCount: {
                    type: 'integer',
                    description: 'Total unread notifications for the user (regardless of pagination).',
                    example: 3,
                  },
                  page: { type: 'integer', example: 1 },
                  pageSize: { type: 'integer', example: 20 },
                  hasNextPage: { type: 'boolean', example: false },
                },
              },
            },
          },
          401: errorSchema('Missing or invalid Bearer token.'),
        },
      },
    },
    async (_request, reply) => {
      return reply.status(200).send({
        data: { items: [], total: 0, unreadCount: 0, page: 1, pageSize: 20, hasNextPage: false },
      });
    },
  );

  // PATCH /notifications/:notificationId/read --------------------------------
  fastify.patch<{ Params: { notificationId: string } }>(
    '/notifications/:notificationId/read',
    {
      schema: {
        tags: ['Notifications'],
        summary: 'Mark notification as read',
        description: 'Marks a single notification as read. Idempotent — calling this on an already-read notification has no effect and returns HTTP 200.',
        security: bearerAuth,
        params: {
          type: 'object',
          required: ['notificationId'],
          properties: {
            notificationId: {
              type: 'string',
              format: 'uuid',
              description: 'ID of the notification to mark as read.',
              example: 'e5f6a7b8-c9d0-1234-efgh-345678901234',
            },
          },
        },
        response: {
          200: {
            description: 'Notification updated.',
            type: 'object',
            required: ['data'],
            properties: { data: notificationSchema },
          },
          401: errorSchema('Missing or invalid Bearer token.'),
          403: errorSchema('Notification belongs to a different user.'),
          404: errorSchema('Notification not found.'),
        },
      },
    },
    async (_request, reply) => {
      return reply.status(404).send({ error: { code: 'NOT_FOUND', message: 'Notification not found' } });
    },
  );

  // POST /notifications/read-all ---------------------------------------------
  fastify.post(
    '/notifications/read-all',
    {
      schema: {
        tags: ['Notifications'],
        summary: 'Mark all notifications as read',
        description: 'Marks **all** unread notifications for the authenticated user as read in a single operation. Returns HTTP 204 whether or not any notifications were actually unread.',
        security: bearerAuth,
        response: {
          204: { description: 'All notifications marked as read. No response body.' },
          401: errorSchema('Missing or invalid Bearer token.'),
        },
      },
    },
    async (_request, reply) => {
      return reply.status(204).send();
    },
  );

  // DELETE /notifications/:notificationId ------------------------------------
  fastify.delete<{ Params: { notificationId: string } }>(
    '/notifications/:notificationId',
    {
      schema: {
        tags: ['Notifications'],
        summary: 'Delete a notification',
        description: 'Permanently deletes a notification. This cannot be undone.',
        security: bearerAuth,
        params: {
          type: 'object',
          required: ['notificationId'],
          properties: {
            notificationId: {
              type: 'string',
              format: 'uuid',
              description: 'ID of the notification to delete.',
              example: 'e5f6a7b8-c9d0-1234-efgh-345678901234',
            },
          },
        },
        response: {
          204: { description: 'Notification deleted.' },
          401: errorSchema('Missing or invalid Bearer token.'),
          403: errorSchema('Notification belongs to a different user.'),
          404: errorSchema('Notification not found.'),
        },
      },
    },
    async (_request, reply) => {
      return reply.status(204).send();
    },
  );
}
