'use client';

import { useState } from 'react';
import { useTranslations } from 'next-intl';
import { cn } from '@/lib/utils';

interface Props {
  /** Full RTMP ingest URL — undefined until the broadcast has started. */
  ingestUrl?: string | null;
  /** Session stream key — undefined until the broadcast has started. */
  streamKey?: string | null;
  className?: string;
}

const MASK_PLACEHOLDER = '••••••••••••••••';

function CopyButton({ value, label, copiedLabel }: { value: string | null; label: string; copiedLabel: string }): React.ReactElement {
  const [copied, setCopied] = useState(false);

  async function handleCopy(): Promise<void> {
    if (!value) return;
    await navigator.clipboard.writeText(value);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  return (
    <button
      type="button"
      onClick={() => void handleCopy()}
      disabled={!value}
      aria-label={copied ? copiedLabel : label}
      title={copied ? copiedLabel : label}
      className="flex h-6 w-6 shrink-0 items-center justify-center rounded text-muted-foreground transition-colors hover:bg-muted hover:text-foreground disabled:cursor-not-allowed disabled:opacity-40"
    >
      {copied ? (
        <svg className="h-3.5 w-3.5 text-green-500" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
          <polyline points="20 6 9 17 4 12" />
        </svg>
      ) : (
        <svg className="h-3.5 w-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
          <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
          <path d="M5 15H4a2 2 0 01-2-2V4a2 2 0 012-2h9a2 2 0 012 2v1" />
        </svg>
      )}
    </button>
  );
}

/**
 * OBS / RTMP ingest details — server URL + masked stream key with copy and
 * eye toggle. Values are generated by the stream-orchestrator when the
 * broadcast starts; until then the card shows a disabled placeholder state.
 */
export function RtmpIngestCard({ ingestUrl, streamKey, className }: Props): React.ReactElement {
  const t = useTranslations('stream');
  const [keyVisible, setKeyVisible] = useState(false);

  const hasKey = Boolean(streamKey);
  const displayedKey = hasKey && keyVisible ? streamKey : MASK_PLACEHOLDER;

  return (
    <div
      className={cn(
        'relative flex aspect-video w-full flex-col justify-center gap-3 rounded-2xl border border-border bg-surface-1 p-4',
        className,
      )}
    >
      <span className="absolute right-3 top-3 text-muted-foreground/50" aria-hidden="true">
        <svg className="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
          <rect x="2" y="14" width="20" height="6" rx="2" />
          <line x1="6" y1="17" x2="6" y2="17" strokeWidth="3" />
          <line x1="10" y1="17" x2="10" y2="17" strokeWidth="3" />
          <path d="M5 14V9a7 7 0 0114 0v5" />
        </svg>
      </span>

      <div>
        <span className="mb-1 block text-[10px] font-bold uppercase tracking-wider text-muted-foreground">
          {t('obs.rtmpUrl')}
        </span>
        <div className="flex items-center justify-between gap-2 rounded-lg bg-surface-0 px-2.5 py-1.5">
          <span className={cn('truncate font-mono text-xs', ingestUrl ? 'text-foreground' : 'text-muted-foreground')}>
            {ingestUrl ?? MASK_PLACEHOLDER}
          </span>
          <CopyButton value={ingestUrl ?? null} label={t('obs.copy')} copiedLabel={t('obs.copied')} />
        </div>
      </div>

      <div>
        <span className="mb-1 block text-[10px] font-bold uppercase tracking-wider text-muted-foreground">
          {t('obs.streamKey')}
        </span>
        <div className="flex items-center justify-between gap-2 rounded-lg bg-surface-0 px-2.5 py-1.5">
          <span className={cn('truncate font-mono text-xs', hasKey && keyVisible ? 'text-foreground' : 'text-muted-foreground')}>
            {displayedKey}
          </span>
          <div className="flex items-center gap-0.5">
            <button
              type="button"
              onClick={() => setKeyVisible((v) => !v)}
              disabled={!hasKey}
              aria-label={keyVisible ? t('obs.hideKey') : t('obs.showKey')}
              title={keyVisible ? t('obs.hideKey') : t('obs.showKey')}
              className="flex h-6 w-6 shrink-0 items-center justify-center rounded text-muted-foreground transition-colors hover:bg-muted hover:text-foreground disabled:cursor-not-allowed disabled:opacity-40"
            >
              {keyVisible ? (
                <svg className="h-3.5 w-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
                  <path d="M17.94 17.94A10.07 10.07 0 0112 20c-7 0-11-8-11-8a18.45 18.45 0 015.06-5.94M9.9 4.24A9.12 9.12 0 0112 4c7 0 11 8 11 8a18.5 18.5 0 01-2.16 3.19M14.12 14.12a3 3 0 11-4.24-4.24" />
                  <line x1="1" y1="1" x2="23" y2="23" />
                </svg>
              ) : (
                <svg className="h-3.5 w-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
                  <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z" />
                  <circle cx="12" cy="12" r="3" />
                </svg>
              )}
            </button>
            <CopyButton value={streamKey ?? null} label={t('obs.copy')} copiedLabel={t('obs.copied')} />
          </div>
        </div>
      </div>

      {!hasKey && (
        <p className="text-xs text-muted-foreground">{t('obs.generatedOnStart')}</p>
      )}
    </div>
  );
}
